# Generated by Django 3.2.5 on 2021-07-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
