# Generated by Django 3.2.5 on 2021-07-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0005_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='post_app.Tag'),
        ),
    ]
